import { NextResponse } from 'next/server'
import { getCabinetContext } from '@/src/lib/cabinetContext'
import { prisma } from '@/src/lib/prisma'

export const dynamic = 'force-dynamic'

type RouteContext = {
  params: Promise<{ id: string }>
}

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;')
}

function formatMoney(amountKzt: number, _currency: string) {
  const rounded = Math.max(0, Math.trunc(amountKzt))
  try {
    return `${new Intl.NumberFormat(undefined, { maximumFractionDigits: 0 }).format(rounded)} KZT`
  } catch {
    return `${rounded} KZT`
  }
}

export async function GET(_: Request, routeContext: RouteContext) {
  const { id } = await routeContext.params
  const invoiceId = id.trim()
  if (!invoiceId) return NextResponse.json({ error: 'Invalid invoice id.' }, { status: 400 })

  try {
    const context = await getCabinetContext({ requireSession: true })
    const invoice = await prisma.invoice.findFirst({
      where: {
        id: invoiceId,
        userId: context.userId,
      },
      include: {
        order: {
          include: {
            bookings: {
              include: {
                room: { select: { name: true } },
                club: { select: { name: true, address: true, city: true, currency: true } },
              },
              orderBy: [{ checkIn: 'asc' }],
            },
          },
        },
      },
    })

    if (invoice) {
      const booking = invoice.order.bookings[0] || null
      const currency = invoice.currency || booking?.club?.currency || 'KZT'
      await prisma.auditLog.create({
        data: {
          clubId: invoice.clubId,
          actorUserId: context.userId,
          action: 'client.invoice.downloaded',
          entityType: 'invoice',
          entityId: invoice.id,
          ...(booking ? { bookingId: booking.id } : {}),
          metadata: JSON.stringify({ format: 'html' }),
        },
      })
      const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Invoice ${escapeHtml(invoice.invoiceNumber)}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 24px; color: #111; }
      .wrap { max-width: 760px; margin: 0 auto; }
      h1 { margin: 0 0 12px; font-size: 24px; }
      .muted { color: #666; font-size: 12px; }
      .row { display: flex; justify-content: space-between; gap: 12px; margin: 6px 0; }
      .box { border: 1px solid #ddd; border-radius: 8px; padding: 12px; margin: 14px 0; }
    </style>
  </head>
  <body>
    <div class="wrap">
      <h1>Booking Receipt</h1>
      <p class="muted">Invoice #${escapeHtml(invoice.invoiceNumber)}</p>
      <div class="box">
        <div class="row"><span>Issued at</span><strong>${escapeHtml(new Date(invoice.issueDate).toLocaleString())}</strong></div>
        <div class="row"><span>Status</span><strong>${escapeHtml(invoice.status)}</strong></div>
        <div class="row"><span>Amount</span><strong>${escapeHtml(formatMoney(invoice.totalCents, currency))}</strong></div>
      </div>
      <div class="box">
        <div class="row"><span>Booking ID</span><strong>${booking ? `#${booking.id}` : 'N/A'}</strong></div>
        <div class="row"><span>Club</span><strong>${escapeHtml(booking?.club?.name || 'Unknown')}</strong></div>
        <div class="row"><span>Location</span><strong>${escapeHtml([booking?.club?.city, booking?.club?.address].filter(Boolean).join(', ') || 'N/A')}</strong></div>
        <div class="row"><span>Room</span><strong>${escapeHtml(booking?.room?.name || 'N/A')}</strong></div>
        <div class="row"><span>Session</span><strong>${booking ? `${escapeHtml(new Date(booking.checkIn).toLocaleString())} - ${escapeHtml(new Date(booking.checkOut).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }))}` : 'N/A'}</strong></div>
      </div>
      <p class="muted">Generated by Booking Project client cabinet.</p>
    </div>
  </body>
</html>`

      return new NextResponse(html, {
        status: 200,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Content-Disposition': `inline; filename="invoice-${invoice.invoiceNumber}.html"`,
        },
      })
    }

    const parsedLegacyInvoiceId = Number(invoiceId)
    if (!Number.isInteger(parsedLegacyInvoiceId) || parsedLegacyInvoiceId < 1) {
      return NextResponse.json({ error: 'Invoice not found.' }, { status: 404 })
    }

    const payment = await prisma.payment.findFirst({
      where: {
        id: parsedLegacyInvoiceId,
        booking: {
          OR: [
            { clientUserId: context.userId },
            ...(context.profile.email ? [{ guestEmail: context.profile.email.toLowerCase() }] : []),
          ],
        },
      },
      include: {
        booking: {
          include: {
            room: { select: { name: true } },
            club: { select: { id: true, name: true, address: true, city: true, currency: true } },
          },
        },
      },
    })
    if (!payment) {
      return NextResponse.json({ error: 'Invoice not found.' }, { status: 404 })
    }

    await prisma.auditLog.create({
      data: {
        clubId: payment.booking.club?.id || payment.booking.clubId,
        actorUserId: context.userId,
        action: 'client.invoice.downloaded',
        entityType: 'invoice',
        entityId: invoiceId,
        bookingId: payment.booking.id,
        metadata: JSON.stringify({ format: 'html' }),
      },
    })

    const currency = payment.booking.priceCurrency || payment.booking.club?.currency || 'KZT'
    const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Receipt ${payment.id}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 24px; color: #111; }
      .wrap { max-width: 760px; margin: 0 auto; }
      h1 { margin: 0 0 12px; font-size: 24px; }
      .muted { color: #666; font-size: 12px; }
      .row { display: flex; justify-content: space-between; gap: 12px; margin: 6px 0; }
      .box { border: 1px solid #ddd; border-radius: 8px; padding: 12px; margin: 14px 0; }
    </style>
  </head>
  <body>
    <div class="wrap">
      <h1>Booking Receipt</h1>
      <p class="muted">Receipt #RCP-${payment.id}</p>
      <div class="box">
        <div class="row"><span>Issued at</span><strong>${escapeHtml(new Date(payment.createdAt).toLocaleString())}</strong></div>
        <div class="row"><span>Status</span><strong>${escapeHtml(payment.status)}</strong></div>
        <div class="row"><span>Method</span><strong>${escapeHtml(payment.method)}</strong></div>
        <div class="row"><span>Amount</span><strong>${escapeHtml(formatMoney(payment.amountCents, currency))}</strong></div>
      </div>
      <div class="box">
        <div class="row"><span>Booking ID</span><strong>#${payment.booking.id}</strong></div>
        <div class="row"><span>Club</span><strong>${escapeHtml(payment.booking.club?.name || 'Unknown')}</strong></div>
        <div class="row"><span>Location</span><strong>${escapeHtml([payment.booking.club?.city, payment.booking.club?.address].filter(Boolean).join(', ') || 'N/A')}</strong></div>
        <div class="row"><span>Room</span><strong>${escapeHtml(payment.booking.room?.name || 'N/A')}</strong></div>
        <div class="row"><span>Session</span><strong>${escapeHtml(new Date(payment.booking.checkIn).toLocaleString())} - ${escapeHtml(new Date(payment.booking.checkOut).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }))}</strong></div>
      </div>
      <p class="muted">Generated by Booking Project client cabinet.</p>
    </div>
  </body>
</html>`

    return new NextResponse(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `inline; filename="receipt-${payment.id}.html"`,
      },
    })
  } catch {
    return NextResponse.json({ error: 'Unauthorized.' }, { status: 401 })
  }
}
